### ISSUE TITLE
Getting Error when creating new patient

### ISSUE THREAD

**Issue by jcbdigitalhub** [ESS-LLP/erpnext#13]
I'm getting error on Patient doctype.  It says Patient Admission Doctype is not found.

**Comment by system19** [comment]
Me too.

**Comment by rkurungadam** [comment]
fixed this, please update.

**Comment by system19** [comment]
Thanks @rkurungadam , But I still get "DocType Patient Admission not found" "The resource you are looking for is not available" errors when selecting the Patient icon or trying to create a New Patient on the default install desktop. 
erpnext 8.0.27
frappe 8.0.69
